version: "3.0"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/pgdata/
    volumes:
      - pgdata:/var/lib/postgresql/pgdata/
    ports:
      - "5432:5432"
  web:
    build: .
    image: greentown-web
    volumes:
      - .:/src/
      - static:/static
      - media:/media
    depends_on:
      - db
    env_file:
      - .env
    environment:
        PY_AUTORELOAD: 1
    command: /bin/bash -c 'pip install -r requirements.txt && ./manage.py runserver 0.0.0.0:8000'

  ui:
    image: node:16.14.2
    volumes:
      - ./client:/src
    ports:
      - "3000:3000"
    command: /bin/bash -c "cd /src/; npm i --legacy-peer-deps; npm run dev"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - static:/static:ro
      - media:/media:ro
    links:
      - web
      - ui
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  pgdata: { }
  static: { }
  media: { }
