# Generated by Django 4.0.6 on 2022-07-23 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=255, verbose_name='регистрационный номер')),
                ('x_coord', models.FloatField(default=0.0, verbose_name='широта')),
                ('y_coord', models.FloatField(default=0.0, verbose_name='долгота')),
                ('crown_radius', models.FloatField(default=0.0, verbose_name='радиус кроны')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='возраст')),
                ('type', models.PositiveSmallIntegerField(choices=[("(1, 'пихта')", 'Pihta'), ("(2, 'ель')", 'El'), ("(3, 'сосна')", 'Sosna'), ("(4, 'лиственница')", 'Listvennica'), ("(5, 'берёза')", 'Bereza'), ("(6, 'липа')", 'Lipa'), ("(7, 'дуб')", 'Dub'), ("(8, 'осина')", 'Osina'), ("(9, 'клён')", 'Klen'), ("(10, 'каштан')", 'Kashtan')], default="(10, 'каштан')", verbose_name='вид')),
                ('condition', models.PositiveSmallIntegerField(choices=[("(1, 'хорошее')", 'Good'), ("(2, 'среднее')", 'Middle'), ("(3, 'плохое')", 'Bad')], default="(1, 'хорошее')", verbose_name='состояние')),
                ('photo_path', models.FilePathField(verbose_name='фото')),
                ('list_tasks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'Tree',
                'verbose_name_plural': 'Trees',
            },
        ),
    ]
